In [4]:
import pandas as pd
import numpy as np

url = "https://github.com/Mithuinps/Moneyball-IPL-Player-Valuation./raw/refs/heads/main/IPL_2008_2026_Merged.xlsx"

df = pd.read_excel(url)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [5]:
df.head()

,event_name,season,match_number,date,city,venue,team1,team2,toss_winner,toss_decision,...,umpire2,tv_umpire,reserve_umpire,match_type,overs_limit,balls_per_over,gender,team_type,team1_players,team2_players
0,Indian Premier League,2007/08,1.0,2008-04-18,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,RE Koertzen,AM Saheba,VN Kulkarni,T20,20,6,male,club,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey..."
1,Indian Premier League,2007/08,2.0,2008-04-19,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,...,SL Shastri,RB Tiffin,MSS Ranawat,T20,20,6,male,club,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ..."
2,Indian Premier League,2007/08,3.0,2008-04-19,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,...,GA Pratapkumar,IL Howell,Unknown,T20,20,6,male,club,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm..."
3,Indian Premier League,2007/08,4.0,2008-04-20,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,...,K Hariharan,Asad Rauf,F Gomes,T20,20,6,male,club,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S..."
4,Indian Premier League,2007/08,5.0,2008-04-20,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,...,DJ Harper,AV Jayaprakash,SN Bandekar,T20,20,6,male,club,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli..."

In [6]:
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

Total Rows: 1243
Total Columns: 31

In [7]:
print("IPL Dataset Column Names:\n")

for column in df.columns:
    print(column)

IPL Dataset Column Names:

event_name
season
match_number
date
city
venue
team1
team2
toss_winner
toss_decision
team1_runs
team1_wickets
team2_runs
team2_wickets
winner
result_type
win_by_runs
win_by_wickets
player_of_match
match_referee
umpire1
umpire2
tv_umpire
reserve_umpire
match_type
overs_limit
balls_per_over
gender
team_type
team1_players
team2_players

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_name       1243 non-null   object
 1   season           1243 non-null   object
 2   match_number     1169 non-null   float64
 3   date             1243 non-null   datetime64[ns]
 4   city             1243 non-null   object
 5   venue            1243 non-null   object
 6   team1            1243 non-null   object
 7   team2            1243 non-null   object
 8   toss_winner      1243 non-null   object
 9   toss_decision    1243 non-null   object
 10  team1_runs       1243 non-null   int64
 11  team1_wickets    1243 non-null   int64
 12  team2_runs       1243 non-null   int64
 13  team2_wickets    1243 non-null   int64
 14  winner           1218 non-null   object
 15  result_type      1243 non-null   object
 16  win_by_runs      1243 non-null   int64
 17  win_by_wickets   1243 non-null   int64
 18  player_of_match  1234 non-null   object
 19  match_referee    1243 non-null   object
 20  umpire1          1243 non-null   object
 21  umpire2          1243 non-null   object
 22  tv_umpire        1243 non-null   object
 23  reserve_umpire   1243 non-null   object
 24  match_type       1243 non-null   object
 25  overs_limit      1243 non-null   int64
 26  balls_per_over   1243 non-null   int64
 27  gender           1243 non-null   object
 28  team_type        1243 non-null   object
 29  team1_players    1243 non-null   object
 30  team2_players    1243 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(8), object(21)
memory usage: 301.2+ KB

In [9]:
print("Missing Values in Each Column:\n")
print(df.isnull().sum())

Missing Values in Each Column:

event_name          0
season              0
match_number       74
date                0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
team1_runs          0
team1_wickets       0
team2_runs          0
team2_wickets       0
winner             25
result_type         0
win_by_runs         0
win_by_wickets      0
player_of_match     9
match_referee       0
umpire1             0
umpire2             0
tv_umpire           0
reserve_umpire      0
match_type          0
overs_limit         0
balls_per_over      0
gender              0
team_type           0
team1_players       0
team2_players       0
dtype: int64

In [10]:
print("Total Duplicate Rows:", df.duplicated().sum())

Total Duplicate Rows: 0

In [11]:
report = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Missing_Values": df.isnull().sum().values,
    "Missing_Percentage": (df.isnull().mean().values * 100).round(2),
    "Unique_Values": df.nunique().values
})

print("IPL DATASET - FIRST IMPRESSION REPORT")
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])
print("Duplicate Rows:", df.duplicated().sum())

display(report)

IPL DATASET - FIRST IMPRESSION REPORT
Total Rows: 1243
Total Columns: 31
Duplicate Rows: 0

,Column,Data_Type,Missing_Values,Missing_Percentage,Unique_Values
0,event_name,object,0,0.00,1
1,season,object,0,0.00,19
2,match_number,float64,74,5.95,72
3,date,datetime64[ns],0,0.00,947
4,city,object,0,0.00,38
5,venue,object,0,0.00,60
6,team1,object,0,0.00,19
7,team2,object,0,0.00,19
8,toss_winner,object,0,0.00,19
9,toss_decision,object,0,0.00,2
10,team1_runs,int64,0,0.00,186
11,team1_wickets,int64,0,0.00,11
12,team2_runs,int64,0,0.00,174
13,team2_wickets,int64,0,0.00,12
14,winner,object,25,2.01,19
15,result_type,object,0,0.00,3
16,win_by_runs,int64,0,0.00,105
17,win_by_wickets,int64,0,0.00,11
18,player_of_match,object,9,0.72,321
19,match_referee,object,0,0.00,32
20,umpire1,object,0,0.00,76
21,umpire2,object,0,0.00,71
22,tv_umpire,object,0,0.00,85
23,reserve_umpire,object,0,0.00,82
24,match_type,object,0,0.00,1
25,overs_limit,int64,0,0.00,1
26,balls_per_over,int64,0,0.00,1
27,gender,object,0,0.00,1
28,team_type,object,0,0.00,1
29,team1_players,object,0,0.00,1225
30,team2_players,object,0,0.00,1223

In [12]:
report.to_csv("Week2_First_Impression_Report.csv", index=False)

print("First Impression Report saved successfully!")

First Impression Report saved successfully!

In [13]:
summary = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Duplicate Rows",
        "Total Missing Values",
        "Columns with Missing Values"
    ],
    "Value": [
        df.shape[0],
        df.shape[1],
        df.duplicated().sum(),
        df.isnull().sum().sum(),
        (df.isnull().sum() > 0).sum()
    ]
})

display(summary)

summary.to_csv("Week2_Dataset_Summary.csv", index=False)

                        Metric  Value
0                   Total Rows   1243
1                Total Columns     31
2               Duplicate Rows      0
3         Total Missing Values    108
4  Columns with Missing Values      3

In [14]:
from google.colab import files

files.download("Week2_First_Impression_Report.csv")

In [15]:
files.download("Week2_Dataset_Summary.csv")